<e>         ::= <log_op>
              | <comp_op>
              | <bool>
<log_op>    ::= and_(<e>,<e>)
              | or_(<e>,<e>)
              | not_(<e>)
              | nand_(<e>,<e>)
              | nor_(<e>,<e>)
              | xor_(<e>,<e>)
              | xnor_(<e>,<e>)
<comp_op>   ::= less_than_or_equal(<num>,<num>)
              | greater_than_or_equal(<num>,<num>)
<num>       ::= <feat>
              | <num_op>
              | <const>
<num_op>    ::= add(<num>,<num>)
              | sub(<num>,<num>)
              | mul(<num>,<num>)
              | aq(<num>, <num>)
              | neg(<num>)
              | psin(<num>)
              | ptanh(<num>)
<const>     ::= <digit>.<digit><digit><digit>
              | -<digit>.<digit><digit><digit>
<digit>     ::= 0
              | 1
              | 2
              | 3
              | 4
              | 5
              | 6
              | 7
              | 8
              | 9
<bool>      ::= 0
              | 1
<feat>      ::= x[15]
              | x[3]
              | x[14]
              | x[13]
              | x[18]
              | x[0]
              | x[16]
              | x[6]
              | x[1]
              | x[20]